### ISSUE TITLE
Eyeballer source code does not include a file requested by Eyeballer

### ISSUE THREAD

**Issue by bfgstroy** [BishopFox/eyeballer#56]
## Description of Bug
Eyeballer requires a file called ``labels.csv``, which is not packaged with the Eyeballer source code.

## What should the expected behavior be
This file should either be included in Eyeballer source code or not required by Eyeballer.

A workaround may be performed by creating a dummy CSV file with a single column labeled *Evaluation*.

## Steps to Reproduce
Perform a new clone of the Eyeballer Git repo and execute a predict function.

**Comment by dan-bishopfox** [comment]
Fixed in 99fd136a0d306976ab31a49721c93920c7fb5370
