### ISSUE TITLE
How to view the html file once eyeballer has finished its search

### ISSUE THREAD

**Issue by tapilon** [BishopFox/eyeballer#58]
Where is the path of the Html file once we have started the prediction using eyeballer. Cant see it nowhere. I'm using the Bishop,h5 file as Weight.

**Comment by dan-bishopfox** [comment]
`results.html` should be in the root repo path. Adjacent to `eyeballer.py`

**Comment by tapilon** [comment]
Can't see it anywhere. I am using the command: python3 eyeballer.py --weights bishop.h5 predict nothing.png

Is there something i should add to the command or anything wrong with it?

**Comment by tapilon** [comment]
Got it.. Nevermind

Thanks
