### ISSUE TITLE
Grouping similar/same images within category

### ISSUE THREAD

**Issue by uBadRequest** [BishopFox/eyeballer#60]
As a persona,
I want to have images grouped that are similar/the same
so that trying to go through thousands of images is less painful.

## Overview
For example, lets say I have taken screenshots of 100 of the same Grafana login page or the IBM Security Access Manager, having all those grouped together rather then scatter throughout the "login" category would be ideal.

**Comment by dan-bishopfox** [comment]
Try looking into "perceptual hashes". If you want to group similar images together, there's already a ton of ways to do that. No need for a neural network.

**Comment by uBadRequest** [comment]
Ahh, I didn't mean for a neural network to do this. When jsresults is created, could sort them then, right?

**Comment by dan-bishopfox** [comment]
Oh, that's fair. I misunderstood. Grouping images together in the UI by similarity would be cool. Reopening

**Comment by dan-bishopfox** [comment]
Hrm, actually now that I think about it, this WOULD be a cool thing to do, just not one that Eyeballer should do. Closing.
