### ISSUE TITLE
Feature request: Add support for Pascal VOC format

### ISSUE THREAD

**Issue by geeknik** [BishopFox/eyeballer#61]
As a system, we would like `eyeballer` to be able to read the `Pascal VOC` format used by ImageNet so we and others may use an app like Labelai to more easily label thousands of images.

## Overview
Labeling images by hand in a CSV file is rather tedious as all interested parties can agree. [Labelai](https://github.com/aralroca/labelai) is a web-based app which can ease our pain. 
```
Labelai is an online tool designed to label images, useful for training AI models.

It's totally client-side, there is no request to any server. It is implemented with Next.js + Preact.

Annotations are saved as XML files in PASCAL VOC format, the format used by ImageNet.
```

Thank you. 

## Acceptance Criteria
- [ ] Security implications approved
- [ ]

#### Non Functional Requirements/Wants
- [ ] 

#### External Documents / Links
Sample Pascal VOC annotation file: https://gist.github.com/Prasad9/30900b0ef1375cc7385f4d85135fdb44

**Comment by dan-bishopfox** [comment]
You could just convert the Pascal VOC file 
https://github.com/akchan/conv_pascal_to_csv
