### ISSUE TITLE
How did you determine if a page is "old looking" when creating training set?

### ISSUE THREAD

**Issue by c-flaherty** [BishopFox/eyeballer#63]
How did you determine if a page is "old-looking" when labeling the training set? Are there any features in particular you looked for? Or did you take a less structured approach and just label according to immediate impressions of engineers on the Bishop Fox team?

**Comment by dan-bishopfox** [comment]
It was all classified by hand, manually, laboriously, one-by-one. Any attempt to automatically lump things into categories based on some heuristic failed miserably. 

Though I got a head-start by going into archive.org and going back to like y2k.

**Comment by c-flaherty** [comment]
> It was all classified by hand, manually, laboriously, one-by-one. Any attempt to automatically lump things into categories based on some heuristic failed miserably.
> 
> Though I got a head-start by going into archive.org and going back to like y2k.

Wow! That must have really taken a long time.
