### ISSUE TITLE
PyTorch version available

### ISSUE THREAD

**Issue by phibenz** [BishopFox/eyeballer#64]
Thank you for this awesome tool. I wanted to let you know, that I created a PyTorch version of it. Additional to the code, I also published the pretrained models and the dataset used to train them. Further instructions can be found, on how to add additional classes and how to generate the dataset in general.
Check it out here: https://github.com/phibenz/eyeballer.pytorch

**Comment by dan-bishopfox** [comment]
Hey that's really cool! I'd love to see what you can make with it! I've been meaning to come back to this and work some more with it. 

Also, I have the full-size screenshot images around here. The model scales them down anyway so it doesn't matter much for eyeballer, but if you wanted to use a different model with a larger size you'd want the full-size images. I can send it to you out-of-band if you'd like it.

**Comment by phibenz** [comment]
Thank you for the offer. I currently have no specific use case for the data set in mind. In case something comes up I would be happy to come back to you, if that is ok for you.
